name: LockedMythics
version: '${version}'

main: org.turbojax.lockedMythics.LockedMythics
description: Allows admins to prevent players from picking up items based on their model or custom model data.
author: TurboJax
api-version: '1.21.11'
website: https://github.com/TurboJax/LockedMythics

libraries:
  - "org.xerial:sqlite-jdbc:${sqliteVersion}"

permissions:
  lockedmythics.addlock:
    description: Allows a player to use /addlock
    default: false
  lockedmythics.getlocks:
    description: Allows a player to use /getlocks
    default: false
  lockedmythics.reloadlocks:
    description: Allows a player to use /reloadlocks
    default: false
  lockedmythics.removelock:
    description: Allows a player to use /removelocks
    default: false
  lockedmythics.admin:
    description: Allows a player to use all the commands
    default: op
    children:
      lockedmythics.addlock: true
      lockedmythics.getlocks: true
      lockedmythics.reloadlocks: true
      lockedmythics.removelock: true

commands:
  addlock:
    description: Adds one or more locks to a player
    usage: "/addlock <player> <locks|*>"
  getlocks:
    description: Gets the locks a player has
    usage: "/getlocks <player>"
  reloadlocks:
    description: Reloads the list of locks from the config
    usage: "/reloadlocks"
  removelock:
    description: Removes one or more locks from a player
    usage: "/removelock <player> <locks|*>"